
/* ═══ CARD IMAGES ═══ */
var WIKI_MAJ=[
  'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_06_Lovers.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg'
];

var WIKI_MINOR={
  'Wands01':'https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg',
  'Wands02':'https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg',
  'Wands03':'https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg',
  'Wands04':'https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg',
  'Wands05':'https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg',
  'Wands06':'https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg',
  'Wands07':'https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg',
  'Wands08':'https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg',
  'Wands09':'https://upload.wikimedia.org/wikipedia/commons/e/e7/Wands09.jpg',
  'Wands10':'https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg',
  'Wands11':'https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg',
  'Wands12':'https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg',
  'Wands13':'https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg',
  'Wands14':'https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg',
  'Cups01':'https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg',
  'Cups02':'https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg',
  'Cups03':'https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg',
  'Cups04':'https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg',
  'Cups05':'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg',
  'Cups06':'https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg',
  'Cups07':'https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg',
  'Cups08':'https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg',
  'Cups09':'https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg',
  'Cups10':'https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg',
  'Cups11':'https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg',
  'Cups12':'https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg',
  'Cups13':'https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg',
  'Cups14':'https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg',
  'Swords01':'https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg',
  'Swords02':'https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg',
  'Swords03':'https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg',
  'Swords04':'https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg',
  'Swords05':'https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg',
  'Swords06':'https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg',
  'Swords07':'https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg',
  'Swords08':'https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg',
  'Swords09':'https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg',
  'Swords10':'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg',
  'Swords11':'https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg',
  'Swords12':'https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg',
  'Swords13':'https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg',
  'Swords14':'https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg',
  'Pents01':'https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg',
  'Pents02':'https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg',
  'Pents03':'https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg',
  'Pents04':'https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg',
  'Pents05':'https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg',
  'Pents06':'https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg',
  'Pents07':'https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg',
  'Pents08':'https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg',
  'Pents09':'https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg',
  'Pents10':'https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg',
  'Pents11':'https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg',
  'Pents12':'https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg',
  'Pents13':'https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg',
  'Pents14':'https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg'
};

window.CARD_CONFIG = {
  // ── 메이저 아르카나 ──
  "major_0": "RWS_Tarot_00_Fool.webp",
  "major_1": "RWS_Tarot_01_Magician.webp",
  "major_2": "RWS_Tarot_02_High_Priestess.webp",
  "major_3": "RWS_Tarot_03_Empress.webp",
  "major_4": "RWS_Tarot_04_Emperor.webp",
  "major_5": "RWS_Tarot_05_Hierophant.webp",
  "major_6": "RWS_Tarot_06_Lovers.webp",
  "major_7": "RWS_Tarot_07_Chariot.webp",
  "major_8": "RWS_Tarot_08_Strength.webp",
  "major_9": "RWS_Tarot_09_Hermit.webp",
  "major_10": "RWS_Tarot_10_Wheel_of_Fortune.webp",
  "major_11": "RWS_Tarot_11_Justice.webp",
  "major_12": "RWS_Tarot_12_Hanged_Man.webp",
  "major_13": "RWS_Tarot_13_Death.webp",
  "major_14": "RWS_Tarot_14_Temperance.webp",
  "major_15": "RWS_Tarot_15_Devil.webp",
  "major_16": "RWS_Tarot_16_Tower.webp",
  "major_17": "RWS_Tarot_17_Star.webp",
  "major_18": "RWS_Tarot_18_Moon.webp",
  "major_19": "RWS_Tarot_19_Sun.webp",
  "major_20": "RWS_Tarot_20_Judgement.webp",
  "major_21": "RWS_Tarot_21_World.webp",

  // ── 마이너 완드 ──
  "minor_wands_ace": "Wands01.webp", "minor_wands_2": "Wands02.webp", "minor_wands_3": "Wands03.webp",
  "minor_wands_4": "Wands04.webp", "minor_wands_5": "Wands05.webp", "minor_wands_6": "Wands06.webp",
  "minor_wands_7": "Wands07.webp", "minor_wands_8": "Wands08.webp", "minor_wands_9": "Wands09.webp",
  "minor_wands_10": "Wands10.webp",
  "minor_wands_page": "Wands11.webp", "minor_wands_knight": "Wands12.webp", "minor_wands_queen": "Wands13.webp", "minor_wands_king": "Wands14.webp",

  // ── 마이너 컵 ──
  "minor_cups_ace": "Cups01.webp", "minor_cups_2": "Cups02.webp", "minor_cups_3": "Cups03.webp",
  "minor_cups_4": "Cups04.webp", "minor_cups_5": "Cups05.webp", "minor_cups_6": "Cups06.webp",
  "minor_cups_7": "Cups07.webp", "minor_cups_8": "Cups08.webp", "minor_cups_9": "Cups09.webp",
  "minor_cups_10": "Cups10.webp",
  "minor_cups_page": "Cups11.webp", "minor_cups_knight": "Cups12.webp", "minor_cups_queen": "Cups13.webp", "minor_cups_king": "Cups14.webp",

  // ── 마이너 소드 ──
  "minor_swords_ace": "Swords01.webp", "minor_swords_2": "Swords02.webp", "minor_swords_3": "Swords03.webp",
  "minor_swords_4": "Swords04.webp", "minor_swords_5": "Swords05.webp", "minor_swords_6": "Swords06.webp",
  "minor_swords_7": "Swords07.webp", "minor_swords_8": "Swords08.webp", "minor_swords_9": "Swords09.webp",
  "minor_swords_10": "Swords10.webp",
  "minor_swords_page": "Swords11.webp", "minor_swords_knight": "Swords12.webp", "minor_swords_queen": "Swords13.webp", "minor_swords_king": "Swords14.webp",

  // ── 마이너 펜타클 ──
  "minor_pentacles_ace": "Pents01.webp", "minor_pentacles_2": "Pents02.webp", "minor_pentacles_3": "Pents03.webp",
  "minor_pentacles_4": "Pents04.webp", "minor_pentacles_5": "Pents05.webp", "minor_pentacles_6": "Pents06.webp",
  "minor_pentacles_7": "Pents07.webp", "minor_pentacles_8": "Pents08.webp", "minor_pentacles_9": "Pents09.webp",
  "minor_pentacles_10": "Pents10.webp",
  "minor_pentacles_page": "Pents11.webp", "minor_pentacles_knight": "Pents12.webp", "minor_pentacles_queen": "Pents13.webp", "minor_pentacles_king": "Pents14.webp"
};